[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
script = 'script'
via_ir = true
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = false
# Exclude old Solidity 0.5.x libraries that are incompatible with our 0.8.20+ contracts
exclude = ['lib/conditional-tokens-market-makers/**', 'lib/conditional-tokens-contracts/**']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fmt]
line_length = 120

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
base = "https://mainnet.base.org"
baseSepolia = "https://sepolia.base.org"
polygon = "https://polygon-rpc.com"
arbitrum = "https://arb1.arbitrum.io/rpc"
optimism = "https://mainnet.optimism.io"
ethereum = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
base = { key = "PLACEHOLDER" }
baseSepolia = { key = "PLACEHOLDER", url = "https://api-sepolia.basescan.org/api" }
polygon = { key = "PLACEHOLDER" }
arbitrum = { key = "PLACEHOLDER" }
optimism = { key = "PLACEHOLDER" }
ethereum = { key = "PLACEHOLDER" }
